### ISSUE TITLE
Update list of Federal Holidays 

### ISSUE THREAD

**Issue by philof** [colmmacc/us-civics-exam-2008-spa#3]
Update "Name two national U.S. holidays" to include Juneteenth.

**Comment by colmmacc** [comment]
I'd love it if Juneteenth were recognized by USCIS and listed at https://www.uscis.gov/sites/default/files/document/questions-and-answers/100q.pdf but it isn't.

**Comment by colmmacc** [comment]
Oh wow, turns out there is a separate list of updates!

https://www.uscis.gov/citizenship/find-study-materials-and-resources/check-for-test-updates
